= Jekyll AsciiDoc Plugin (powered by Asciidoctor)
Dan Allen

A http://jekyllrb.com[Jekyll] plugin that converts http://asciidoc.org[AsciiDoc] files in your site source to HTML pages using http://asciidoctor.org[Asciidoctor].

== Installation

The plugin depends on the http://rubygems.org/gems/asciidoctor[asciidoctor] gem.
You can install this gem using:

 $ gem install asciidoctor

To install this plugin, copy +asciidoc_converter.rb+ to the +_plugins+ directory in the root of your site source (if no +_plugins+ directory exists, first create it.)

== Configuration

By default, this plugin uses Asciidoctor to convert AsciiDoc files.
Since Asciidoctor is the only option, the default setting is equivalent to the following configuration in +_config.yml+:

 asciidoc: asciidoctor

To tell Jekyll which extensions to recognize as AsciiDoc files, add the following line to your +_config.yml+:

 asciidoc_ext: asciidoc,adoc,ad

The extensions shown in the previous listing are the default values, so you don't need to specify this option if those defaults are sufficient.

To pass attributes to AsciiDoc, add the following line to your +_config.yml+:

 asciidoctor: 'notitle! hardbreaks'

Again, the default values are shown here.
