= Jekyll AsciiDoc Plugin (powered by Asciidoctor)
Paul Rayner <https://github.com/paulrayner[@paulrayner]>; Dan Allen <https://github.com/mojavelinux[@mojavelinux]>
// Settings:
:idprefix:
:idseparator: -
ifndef::env-github[:icons: font]
ifdef::env-github,env-browser[]
:toc: preamble
:toclevels: 1
endif::[]
ifdef::env-github[]
:status:
:outfilesuffix: .adoc
:!toc-title:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]
// Aliases:
:path-config: pass:q[[path]___config.yml__]
// URIs:
:uri-asciidoc: http://asciidoc.org
:uri-asciidoctor: http://asciidoctor.org
:uri-gem-asciidoctor: http://rubygems.org/gems/asciidoctor 
:uri-gem-jekyll-asciidoc: http://rubygems.org/gems/jekyll-asciidoc
:uri-repo: https://github.com/asciidoctor/jekyll-asciidoc
:uri-jekyll: https://jekyllrb.com
:uri-front-matter: http://jekyllrb.com/docs/frontmatter/
:uri-liquid-templates: https://jekyllrb.com/docs/templates/
:uri-graphviz: http://www.graphviz.org

ifdef::status[]
image:https://img.shields.io/gem/v/jekyll-asciidoc.svg?label=gem%20version[Gem Version, link={uri-gem-jekyll-asciidoc}]
image:https://img.shields.io/travis/asciidoctor/jekyll-asciidoc/master.svg[Build Status (Travis CI), link=https://travis-ci.org/asciidoctor/jekyll-asciidoc]
endif::[]

A plugin for {uri-jekyll}[Jekyll] (>= 2.3.0) that converts {uri-asciidoc}[AsciiDoc] files in your site source to HTML pages using {uri-asciidoctor}[Asciidoctor] (>= 1.5.0).

== Overview

The plugin consists of three extensions:

`Jekyll::Converters::AsciiDocConverter`::
  Converts AsciiDoc files to HTML.
`Jekyll::Generators::AsciiDocPreprocessor`::
  Promotes select AsciiDoc attributes to Jekyll front matter (e.g., title, author, page-layout, page-*).
`Jekyll::Filters.asciidocify`::
  A Liquid filter for converting AsciiDoc content to HTML using the converter from this plugin.

These extensions are loaded automatically when the jekyll-asciidoc gem is required.

This plugin currently uses Asciidoctor to convert AsciiDoc content.

== Installation

This plugin is packaged as a gem named jekyll-asciidoc and published to RubyGems.org.
The plugin depends on the {uri-gem-asciidoctor}[asciidoctor] gem, which gets installed automatically.

Your method of installation will depend on whether or not you are using Bundler to manage the dependencies for your Jekyll project.

=== Installing Using Bundler

If you are using Bundler to manage the dependencies for your project (recommended), simply add the `jekyll-asciidoc` plugin gem to your [path]_Gemfile_:

[source,ruby]
----
group :jekyll_plugins do
  gem 'jekyll-asciidoc'
end
----

Then, run the `bundle` command from Bundler to install the gem:

 $ bundle

=== Manual Installation

If you're not using Bundler to manage the dependencies for your Jekyll project, you'll need to install the gem manually:

 $ [sudo] gem install jekyll-asciidoc

NOTE: The `sudo` prefix is only required if you are installing gems into your system.
To avoid this bad practice, we recommend using RVM (or another Ruby version manager), which sets up Ruby safely in your home directory.

Then add the `jekyll-asciidoc` gem to the list of gems for Jekyll to load in your site's {path-config} file:

[source,yaml]
----
gems:
  - jekyll-asciidoc
----

== Creating Pages

This plugin converts eligible AsciiDoc files located inside the source directory (by default, the project root) to HTML pages in the generated site.
There are a few conditions that must be met in order for an AsciiDoc file to be eligible:

. The file must have an AsciiDoc file extension (see <<configuration>>).
. The name of the file must not begin with a dot (`.`) or an underscore (`_`).footnoteref:[excluded_files,These files are excluded by Jekyll.]
. The file must not be located in a folder whose name begins with a dot (`.`) or an underscore (`_`), unless the folder is a designated collection (e.g., posts).footnoteref:[excluded_files]
. With the exception of posts, documents must begin with a {uri-front-matter}[front matter header] if using a version of this plugin < 2.0.0.
Since version 2.0.0 of this plugin, the front matter header is always optional.

Here's a sample AsciiDoc file that meets these criteria:

.sample.adoc
[source,asciidoc]
----
---
layout: page
permalink: /page/
---
= Sample Page
:uri-asciidoctor: http://asciidoctor.org

This is a sample page composed in AsciiDoc.
Jekyll converts it to HTML using {uri-asciidoctor}[Asciidoctor].

[source,ruby]
puts "Hello, World!"
----

Alternatively, you can define the front matter data directly in the AsciiDoc header, which we recommend:

.sample.adoc
[source,asciidoc]
----
= Sample Page
:page-layout: page
:page-permalink: /page/
:uri-asciidoctor: http://asciidoctor.org

This is a sample page composed in AsciiDoc.
Jekyll converts it to HTML using {uri-asciidoctor}[Asciidoctor].

[source,ruby]
puts "Hello, World!"
----

AsciiDoc attributes defined in the document header whose names begin with `page-` get promoted to Jekyll front matter.
The part of the name after the `page-` prefix is used as the entry's key (e.g., page-layout becomes layout) and the value is interpeted as https://en.wikipedia.org/wiki/YAML[YAML] data (that which can be expressed in a single line).

The most commonly defined page variable is layout, which determines which layout is used to wrap the generated content.
Jekyll will look for a file inside the [path]_{empty}_layouts_ folder whose root name matches the name of the layout.
For example, if the layout variable has the value `page`, Jekyll might resolve a layout named [path]_page.html_.

If the layout is empty, the default layout is used, `default` for pages and `posts` for posts.
If the layout is unset or `false`, the AsciiDoc processor will generate a standalone document (`header_footer: true`).
In this case, the page will appear like an HTML file that is generated by the AsciiDoc processor directly.
If the layout is ~, no layout is applied.

To review, here are the different ways to specify a layout using the AsciiDoc attribute page-layout:

* `:page-layout: page` -- use the layout named `page` (e.g., [path]_page.html_)
* _not specified_, `:page-layout:` or `:page-layout: _auto` -- use the default layout (i.e., `default` for pages, `post` for posts)
* `:!page-layout:` or `:page-layout: false` -- don't use a layout; instead, generate a standalone HTML document
* `:page-layout: ~` -- don't use a layout (often results in an incomplete HTML file)

In addition to page attributes defined explicitly, the following implicit AsciiDoc attributes are also promoted to page data:

* doctitle (i.e., the document title) (becomes title)
* author
* revdate (becomes date; value is converted to a DateTime object; only for posts)

Unlike other content files, the {uri-liquid-templates}[Liquid template preprocessor] is not applied to AsciiDoc files by default (as of version 2.0.0 of this plugin).
If you want the Liquid template preprocessor to be applied to an AsciiDoc file (prior to the content being passed to the AsciiDoc processor), you must enable it by setting the liquid page variable.

----
:page-liquid:
----

IMPORTANT: AsciiDoc files may include a {uri-front-matter}[front matter header] for defining page settings and variables.
If present, the front matter header must be the very first character of the file.
The front matter header won't be seen--and could disrupt conversion--if the front matter is preceded by a whitespace character or a Byte Order Mark (BOM).

NOTE: As of version 2.0.0 of this plugin, you may exclude the front matter header, as shown in the second example above.
Prior to version 2.0.0, you had to include at least an empty front matter header (except for posts).
In these cases, you define all the page metadata (e.g., layout) using AsciiDoc attributes instead of in the front matter.
You can also use a combination of both.
When intermixed, the attributes defined in the AsciiDoc header take precedence.

You can now build your site using:

 $ jekyll build

and preview it using:

 $ jekyll serve

If you're using Bundler, then prefix the commands with `bundle exec`, as in:

 $ bundle exec jekyll build

To see a report of all the files that are processed, add the `--verbose` flag:

 $ jekyll build --verbose

If an AsciiDoc file is not listed, then likely Jekyll did not find a {uri-front-matter}[front matter header].

IMPORTANT: If you use the `--safe` option, the AsciiDoc plugin will not be activated.
The `--safe` flag disables third-party plugins such as this one.

== Configuration

This section describes the configuration options for this plugin, which are all _optional_.

=== AsciiDoc

NOTE: Prior to version 2.0.0 of this plugin, the configuration keys in this section were defined as flat, top-level names (e.g., `asciidoc_ext`).
These names are now deprecated, but still supported.

By default, this plugin uses Asciidoctor to convert AsciiDoc files.
Since Asciidoctor is currently the only option, the default setting is equivalent to the following configuration in {path-config}:

[source,yaml]
----
asciidoc:
  processor: asciidoctor
----

IMPORTANT: The `asciidoc` block should only appear _once_ inside {path-config}.
If you define any other options that are documented in this section, you should append them to the `asciidoc` block.

To tell Jekyll which file extensions to match as AsciiDoc files, append the `ext` option to the `asciidoc` block of your {path-config}:

[source,yaml]
----
asciidoc:
  ext: asciidoc,adoc,ad
----

The extensions shown in the previous listing are the default values, so you don't need to specify this option if those defaults are sufficient.

AsciiDoc attributes defined in the document header whose names begin with `page-` are promoted to Jekyll front matter.
The part of the name after the `page-` prefix is used as the key (e.g., page-layout becomes layout).
If you want to change this attribute prefix, append the `page_attribute_prefix` option to the `asciidoc` block of your {path-config}:

[source,yaml]
----
asciidoc:
  page_attribute_prefix: jekyll
----

A hyphen is automatically added to the value of this configuration setting if the value is non-empty.

Since version 2.0.0 of this plugin, all non-hidden AsciiDoc files are processed by default, even those without a front matter header.
If you only want files containing a front matter header to be processed (as was the behavior prior to version 2.0.0), add the `require_front_matter_header` option to the `asciidoc` block of your {path-config}:

[source,yaml]
----
asciidoc:
  require_front_matter_header: true
----

=== Asciidoctor

To pass additional attributes to AsciiDoc, or override the default attributes defined in the plugin, add the following lines to your {path-config}:

[source,yaml]
----
asciidoctor:
  attributes:
    - idprefix=_
    - source-highlighter=pygments
    - pygments-css=style
----

In addition to `attributes`, you can define any another option key (e.g., `safe`) that is recognized by the http://asciidoctor.org/docs/user-manual/#ruby-api-options[Asciidoctor API].

==== Enabling Hard Line Breaks

Many Jekyll users are used to writing in GitHub-flavored Markdown (GFM), which preserves hard line breaks in paragraph content.
Asciidoctor supports this feature for AsciiDoc files.
(In fact, previous versions of this plugin enabled this behavior by default).
If you want to enable this behavior for AsciiDoc files, add the `hardbreaks-option` attribute to the Asciidoctor attributes configuration in your site's {path-config} file:

[source,yaml]
----
asciidoctor:
  attributes:
    - hardbreaks-option
----

If you want to allow individual files to override this setting, then assign the value `@` to the attribute:

[source,yaml]
----
asciidoctor:
  attributes:
    - hardbreaks-option=@
----

If you already have AsciiDoc attributes defined in the {path-config}, the new attribute should be added as a sibling entry in the YAML collection.

WARNING: Keep in mind, if you enable hard line breaks, you won't be able to use the http://asciidoctor.org/docs/asciidoc-recommended-practices/#one-sentence-per-line[one sentence-per-line writing technique].

== Customizing the Generated HTML

You can use templates to customize the HTML output that Asciidoctor generates for your site.
Template files can be composed in any templating language that is supported by https://github.com/rtomayko/tilt[Tilt].
Each template file corresponds to a node in the AsciiDoc document tree (aka AST).

Below are the steps you need to take to configure Asciidoctor to use custom templates with your site.

=== Step 1: Add Required Gems

You'll first need to add the thread_safe gem as well as the gem for the templating language you plan to use.
We'll assume that you are using Slim.

[source,ruby]
----
gem 'slim', '~> 3.0.7'
gem 'thread_safe', '~> 0.3.5'
----

=== Step 2: Install New Gems

Now run the `bundle` command to install the new gems.

 $ bundle

=== Step 3: Create a Templates Folder

Next, create a new folder in your site named [path]___templates__ to store your templates.

 $ mkdir _templates

=== Step 4: Configure Asciidoctor to Load Templates

In your site's {path-config} file, configure Asciidoctor to load the templates by telling it the location where the templates are stored.

[source,yaml]
----
asciidoctor:
  template_dir: _templates
  attributes: ...
----

=== Step 5: Compose a Template

The final step is to compose a template.
We'll be customizing the unordered list node.
Name the file [path]_ulist.html.slim_.

.ulist.html.slim
[source,slim]
----
- if title?
  figure.list.unordered id=id
    figcaption=title
    ul class=[style, role]
      - items.each do |_item|
        li
          span.primary=_item.text
          - if _item.blocks?
            =_item.content
- else
  ul id=id class=[style, role]
    - items.each do |_item|
      li
        span.primary=_item.text
        - if _item.blocks?
          =_item.content
----

The next time you build your site, Asciidoctor will use your custom template to generate the HTML for unordered lists.

TIP: You can find additional examples of custom templates in the https://github.com/asciidoctor/asciidoctor-backends[asciidoctor-backends] repository.

== Enabling Asciidoctor Diagram

Asciidoctor Diagram is a set of extensions for Asciidoctor that allow you to embed diagrams written using the PlantUML, Graphviz, ditaa, or Shaape syntax inside your AsciiDoc documents.

[IMPORTANT]
For Graphviz and PlantUML diagram generation, {uri-graphviz}[Graphviz] must be installed (i.e., the `dot` utility must be available on your `$PATH`.

=== Installation

Using Bundler::
+
--
Add `asciidoctor-diagram` gem to your [path]_Gemfile_:

[source,ruby]
----
group :jekyll_plugins do
  gem 'asciidoctor-diagram', '~> 1.4.0' <1>
  gem 'jekyll-asciidoc'
  ...
end
----
<1> version can be configured differently

Then, run the Bundler command to install it:

 $ bundle install
--

Without Bundler::
+
--
Install gems manually

 $ [sudo] gem install asciidoctor-diagram

Then, add the `asciidoctor-diagram` gem to the list of gems for Jekyll to load in your site's {path-config} file:

[source,yaml]
----
gems:
  - asciidoctor-diagram
  - jekyll-asciidoc
----
--

Both of the previous configurations are the equivalent of passing `-r asciidoctor-diagram` to the `asciidoctor` command.

=== Generated Image Location

By default diagram images are generated in the root folder.
Thus, images URLs are not properly referenced from the generated HTML pages.

To fix this, set the `imagesdir` attribute in any AsciiDoc file that contains diagrams.

._posts/2015-12-24-diagrams.adoc
[source,asciidoc]
----
= Diagrams
:imagesdir: /images/2015-12-24 <1>

[graphviz, dot-example, svg]
....
digraph g {
    a -> b
    b -> c
    c -> d
    d -> a
}
....
----
<1> the date in the imagesdir value must match the date of the post (e.g., 2015-12-24)

WARNING: The images are generated after Jekyll copies assets to the [path]_{empty}_site_ directory.
Therefore, you'll have to run `jeykll` twice before you see the images in the preview.

== Supplemental AsciiDoc Assets

Certain Asciidoctor features, such as icons, require additional CSS rules and other assets to work.
These CSS rules and other assets do not get automatically included in the pages generated by Jekyll.
This section documents how to configure these additional resources.

TIP: If you want to take a shortcut that skips all this configuration, clone the https://github.com/asciidoctor/jekyll-asciidoc-quickstart[Jekyll AsciiDoc Quickstart (JAQ)] repository and use it as a starting point for your site.
JAQ provides a page layout out of the box configured to fully style body content generated from AsciiDoc.

=== Setup

The Jekyll AsciiDoc plugin converts AsciiDoc to embeddable HTML.
This HTML is then inserted into the page layout.
You need to augment the page layout to include resources typically present in a standalone HTML document that Asciidoctor produces.

. Create a stylesheet in the [path]_css_ directory named [path]_asciidoc.css_ to hold additional CSS for body content generated from AsciiDoc.
. Add this stylesheet to the HTML `<head>` in [path]_{empty}_includes/head.html_ under the main.css declaration:
+
[source,html]
----
<link rel="stylesheet" href="{{ "/css/asciidoc.css" | prepend: site.baseurl }}">
----

=== Font-based Admonition and Inline Icons

To enable font-based admonition and inline icons, you first need to add Font Awesome to [path]_{empty}_includes/head.html_ file under the asciidoc.css declaration:

[source,html]
----
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css">
----

NOTE: You can also link to local copy of Font Awesome.

Next, you need to add the following CSS rules from the default Asciidoctor stylesheet to the [path]_css/asciidoc.css_ file:

[source,css]
----
span.icon>.fa {
  cursor: default;
}
.admonitionblock td.icon {
  text-align: center;
  width: 80px;
}
.admonitionblock td.icon [class^="fa icon-"] {
  font-size: 2.5em;
  text-shadow: 1px 1px 2px rgba(0,0,0,.5);
  cursor: default;
}
.admonitionblock td.icon .icon-note:before {
  content: "\f05a";
  color: #19407c;
}
.admonitionblock td.icon .icon-tip:before {
  content: "\f0eb";
  text-shadow: 1px 1px 2px rgba(155,155,0,.8);
  color: #111;
}
.admonitionblock td.icon .icon-warning:before {
  content: "\f071";
  color: #bf6900;
}
.admonitionblock td.icon .icon-caution:before {
  content: "\f06d";
  color: #bf3400;
}
.admonitionblock td.icon .icon-important:before {
  content: "\f06a";
  color: #bf0000;
}
----

Feel free to modify the CSS to your liking.

Finally, you need to enable the font-based icons in the header of the document:

[source,asciidoc]
----
:icons: font
----

or in the site configuration:

[source,yaml]
----
asciidoctor:
  attributes:
    - icons=font
    ...
----

=== Image-based Admonition and Inline Icons

As an alternative to font-based icons, you can configure Asciidoctor to use image-based icons.
In this case, all you need to do is provide the icons at the proper location.

First, enable image-based icons and configure the path to the icons in the header of the document:

[source,asciidoc]
----
:icons:
:iconsdir: /images/icons
----

or your site configuration:

[source,yaml]
----
asciidoctor:
  attributes:
    - icons
    - iconsdir=/images/icons
----

Then, simply put the icon images that the page needs in the [path]_images/icons_ directory.

== GitHub Pages

GitHub doesn't (yet) whitelist the AsciiDoc plugin, so you can only run it on your own machine.

TIP: GitHub needs to hear from enough users that they want to plugin in order to enable it.
Our recommendation is to keep lobbying for them to enable it.

You can automate publishing of the generated site to GitHub Pages using a continuous integration job.
Refer to the tutorial http://eshepelyuk.github.io/2014/10/28/automate-github-pages-travisci.html[Automate GitHub Pages publishing with Jekyll and Travis CI^] to find step-by-step instructions to setup this job.
You can also refer to the https://github.com/johncarl81/transfuse-site[Tranfuse website build^] for an example in practice.

Refer to the https://help.github.com/articles/using-jekyll-plugins-with-github-pages[Jekyll Plugins on GitHub Pages] for a list of the plugins currently supported on the server-side (in addition to Markdown, which isn't listed).

== Development

To help develop the Jekyll AsciiDoc plugin, or to simply use the development version, you need to retrieve the source from GitHub.
Follow the instructions below to learn how to clone the source, run the tests and install the development version.

=== Retrieve the Source Code

You can retrieve the source code from GitHub using git.
Simply copy the URL of the {uri-repo}[GitHub repository] and pass it to the `git clone` command:

[subs=attributes+]
....
git clone {uri-repo}
....

Next, switch to the project directory.

 $ cd jekyll-asciidoc

=== Install the Dependencies

The dependencies needed to develop the Jekyll AsciiDoc plugin are defined in the [path]_Gemfile_ at the root of the project.
You'll use Bundler to install these dependencies.

To check if you have Bundler installed, use the `bundle` command to query for the version:

 $ bundle --version

If Bundler is not installed, use the `gem` command to install it.

 $ [sudo] gem install bundler

Finally, invoke the `bundle` command (which is provided by the bundler gem) from the root of the project to install the dependencies into the project:

 $ bundle --path=.bundle/rubygems

IMPORTANT: Since we've installed dependencies inside the project, it's necessary to prefix all commands (e.g., rake) with `bundle exec`.

=== Running the Tests

The tests are based on RSpec.
The test suite is located in the [path]_spec_ directory.

You can run the tests using Rake.

 $ bundle exec rake spec

For more fine-grained control, you can also run the tests using RSpec directly.

 $ bundle exec rspec

=== Installing the Gem Locally

You can install the development version of the gem as follows:

 $ bundle exec rake install

This allows you to use an unreleased version of the gem in your site.
If you want to build the gem and install it manually, use these commands instead:

 $ bundle exec rake build
 $ [sudo] gem install pkg/jekyll-asciidoc-*.dev.gem

=== Releasing the Gem

When you are ready for a release, first set the version in the file [path]_lib/jekyll-asciidoc/version.rb_.
Then, commit the change using the following commit message template:

 Release X.Y.Z

where `X.Y.Z` is the version number of the gem.

Next, package, tag and release the gem to RubyGems.org, run the following rake task:

 $ bundle exec rake release

IMPORTANT: Ensure you have the proper credentials setup as described in the guide http://guides.rubygems.org/publishing/#publishing-to-rubygemsorg[Publishing to RubyGems.org].

Once you finish the release, you should update the version to the next micro version in the sequence using the `.dev` suffix (e.g., 1.0.1.dev).
