= Jekyll AsciiDoc Plugin (powered by Asciidoctor)
Paul Rayner <https://github.com/paulrayner[@paulrayner]>; Dan Allen <https://github.com/mojavelinux[@mojavelinux]>
// Settings:
:idprefix:
:idseparator: -
ifndef::env-github[:icons: font]
ifdef::env-github,env-browser[]
:toc: preamble
:toclevels: 1
endif::[]
ifdef::env-github[]
:status:
:outfilesuffix: .adoc
:!toc-title:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]
// URIs:
:uri-asciidoc: http://asciidoc.org
:uri-asciidoctor: http://asciidoctor.org
:uri-gem-asciidoctor: http://rubygems.org/gems/asciidoctor 
:uri-gem-jekyll-asciidoc: http://rubygems.org/gems/jekyll-asciidoc
:uri-jekyll: https://jekyllrb.com
:uri-front-matter: http://jekyllrb.com/docs/frontmatter/
:uri-liquid-templates: https://jekyllrb.com/docs/templates/
:uri-graphviz: http://www.graphviz.org

ifdef::status[]
image:https://img.shields.io/gem/v/jekyll-asciidoc.svg?label=gem%20version[Gem Version, link={uri-gem-jekyll-asciidoc}]
endif::[]

A plugin for {uri-jekyll}[Jekyll] (>= 2.0.0) that converts {uri-asciidoc}[AsciiDoc] files in your site source to HTML pages using {uri-asciidoctor}[Asciidoctor].

== Overview

The plugin consists of three extensions:

`Jekyll::Converters::AsciiDocConverter`::
  Converts AsciiDoc files to HTML
`Jekyll::Generators::AsciiDocPreprocessor`::
  Promotes select AsciiDoc attributes to Jekyll front matter (e.g., title, author, page-layout)
`Jekyll::Filters.asciidocify`::
  A Liquid filter for converting AsciiDoc content to HTML using the AsciiDocConverter

These extensions are loaded automatically when the jekyll-asciidoc gem is required.

== Installation

The plugin depends on the {uri-gem-asciidoctor}[asciidoctor] gem.
You can install the gem directly using:

 $ gem install asciidoctor

If you're using Bundler to manage dependencies in your Jekyll project, add the asciidoctor gem to your project's [path]_Gemfile_ instead (just below the entry for the jekyll gem):

[source,ruby]
----
source 'https://rubygems.org'

gem 'jekyll'
gem 'asciidoctor'
----

Then, run the `bundle` command from Bundler to install the gem:

 $ bundle

=== Installing a released version of the plugin

Using Bundler::
+
--
Add the `jekyll-asciidoc` plugin gem to your [path]_Gemfile_

[source,ruby]
----
group :jekyll_plugins do
  gem 'jekyll-asciidoc'
end
----

Then, run the Bundler command to install it:

 $ bundle install
--

Without Bundler::
+
--
If you are not using Bundler for managing Jekyll then install gems manually

 $ gem install jekyll-asciidoc

And then, add the `jekyll-asciidoc` gem to the list of gems for Jekyll to load in your site's [path]_{empty}_config.yml_ file:

[source,yaml]
----
gems:
  - jekyll-asciidoc
----
--

=== Installing development version of the plugin

To install the development version of this plugin, use:

 $ rake install

An alternative--though not recommend--approach is to copy the file [path]_lib/jekyll-asciidoc.rb_ to the [path]_{empty}_plugins_ directory in the root of your site source.

NOTE: If the [path]_{empty}_plugins_ directory does not exist, you need to first create it.

== Creating pages

This plugin converts eligible AsciiDoc files found inside the source directory (typically the project root) to pages in the generated site.
There are a few conditions that must be met for an AsciiDoc file to be qualified:

. The file must have an AsciiDoc file extension (see <<configuration>>).
. The name of the file must not begin with a dot (`.`) or underscore (`_`).footnoteref:[excluded_files,These files are excluded by Jekyll.]
. The file must not be located in a folder whose name begins with a dot (`.`) or underscore (`_`), except for posts.footnoteref:[excluded_files]
. _(optional)_ The document may begin with a {uri-front-matter}[front matter header].

Here's a sample AsciiDoc file that meets these criteria:

.sample.adoc
[source,asciidoc]
----
---
layout: page
permalink: /page/
---
= Sample Page
:uri-asciidoctor: http://asciidoctor.org

This is a sample page composed in AsciiDoc.
Jekyll converts it to HTML using {uri-asciidoctor}[Asciidoctor].

[source,ruby]
puts "Hello, World!"
----

Alternatively, you can define the front matter data directly in the AsciiDoc header (which we recommend):

.sample.adoc
[source,asciidoc]
----
= Sample Page
:page-layout: page
:page-permalink: /page/
:uri-asciidoctor: http://asciidoctor.org

This is a sample page composed in AsciiDoc.
Jekyll converts it to HTML using {uri-asciidoctor}[Asciidoctor].

[source,ruby]
puts "Hello, World!"
----

AsciiDoc attributes defined in the document header whose names begin with `page-` get promoted to Jekyll front matter.
The part of the name after the `page-` prefix is used as the entry's key (e.g., page-layout becomes layout) and the value is interpeted as https://en.wikipedia.org/wiki/YAML[YAML] data (that which can be expressed in a single line).

The most commonly defined page variable is layout, which determines which layout is used to wrap the generated content.
Jekyll will look for a file inside the [path]_{empty}_layouts_ folder whose root name matches the name of the layout.
For example, if the layout variable has the value `page`, Jekyll might resolve a layout named [path]_page.html_.

If the layout is empty, the default layout is used, `default` for pages and `posts` for posts.
If the layout is unset or `false`, the AsciiDoc processor will generate a standalone document (`header_footer: true`).
In this case, the page will appear like an HTML file that is generated by the AsciiDoc processor directly.
If the layout is ~, no layout is applied.

To review, here are the different ways to specify a layout using the AsciiDoc attribute page-layout:

* `:page-layout: page` -- use the layout named `page` (e.g., [path]_page.html_)
* _not specified_, `:page-layout:` or `:page-layout: _auto` -- use the default layout (i.e., `default` for pages, `post` for posts)
* `:!page-layout:` or `:page-layout: false` -- don't use a layout; instead, generate a standalone HTML document
* `:page-layout: ~` -- don't use a layout (often results in an incomplete HTML file)

In addition to page attributes defined explicitly, the following implicit AsciiDoc attributes are also promoted to page data:

* doctitle (i.e., the document title) (becomes title)
* author
* revdate (becomes date; value is converted to a DateTime object; only for posts)

Unlike other content files, the {uri-liquid-templates}[Liquid template preprocessor] is not applied to AsciiDoc files by default (as of v1.2.0 of this plugin).
If you want the Liquid template preprocessor to be applied to an AsciiDoc file (prior to the content being passed to the AsciiDoc processor), you must enable it by setting the liquid page variable.

----
:page-liquid:
----

IMPORTANT: AsciiDoc files may include a {uri-front-matter}[front matter header] for defining page settings and variables.
If present, the front matter header must be the very first character of the file.
The front matter header won't be seen--and could disrupt conversion--if the front matter is preceded by a whitespace character or a Byte Order Mark (BOM).

TIP: You can exclude the front matter header, as shown in the first example above, or leave it empty, as shown in the second example.
In these cases, you'll define all the page metadata (e.g., layout) using AsciiDoc attributes instead of in the front matter.
You can also use a combination of both.
When intermixed, the attributes defined in the AsciiDoc header take precedence.

You can now build your site using:

 $ jekyll build

and preview it using:

 $ jekyll serve

If you're using Bundler, then prefix the commands with `bundle exec`, as in:

 $ bundle exec jekyll build

To see a report of all the files that are processed, add the `--verbose` flag:

 $ jekyll build --verbose

If an AsciiDoc file is not listed, then likely Jekyll did not find a {uri-front-matter}[front matter header].

IMPORTANT: If you use the `--safe` option, the AsciiDoc plugin will not be activated.
The `--safe` flag disables third-party plugins such as this one.

== Configuration

This section describes the configuration options for this plugin, which are _optional_.

By default, this plugin uses Asciidoctor to convert AsciiDoc files.
Since Asciidoctor is the only option, the default setting is equivalent to the following configuration in [path]_{empty}_config.yml_:

[source,yaml]
----
asciidoc: asciidoctor
----

To tell Jekyll which extensions to recognize as AsciiDoc files, add the following line to your [path]_{empty}_config.yml_:

[source,yaml]
----
asciidoc_ext: asciidoc,adoc,ad
----

The extensions shown in the previous listing are the default values, so you don't need to specify this option if those defaults are sufficient.

AsciiDoc attributes defined in the document header whose names begin with `page-` are promoted to Jekyll front matter.
The part of the name after the `page-` prefix is used as the key (e.g., page-layout becomes layout).
If you want to change this attribute prefix, add the following line to your [path]_{empty}_config.yml_:

[source,yaml]
----
asciidoc_page_attribute_prefix: jekyll
----

A hyphen is automatically added to the value of this configuration setting if the value is non-empty.

To pass additional attributes to AsciiDoc, or override the default attributes defined in the plugin, add the following lines to your [path]_{empty}_config.yml_:

[source,yaml]
----
asciidoctor:
  attributes:
    - hardbreaks!
    - source-highlighter=pygments
    - pygments-css=style
----

=== Disabling hard line breaks

The Jekyll AsciiDoc integration is configured to preserve hard line breaks in paragraph content by default.
Since many Jekyll users are used to writing in GitHub-flavored Markdown (GFM), this default was selected to ease the transition to AsciiDoc.
If you want the standard AsciiDoc behavior of collapsing hard line breaks in paragraph content, add the following settings to your site's [path]_{empty}_config.yml_ file:

[source,yaml]
----
asciidoctor:
  attributes:
    - hardbreaks!
----

If you already have AsciiDoc attributes defined in the [path]_{empty}_config.yml_, the `hardbreaks!` attribute should be added as a sibling entry in the YAML collection.

== Enabling Asciidoctor Diagram (optional)

Asciidoctor Diagram is a set of extensions for Asciidoctor that allow you to embed diagrams written using the PlantUML, Graphviz, ditaa, or Shaape syntax inside your AsciiDoc documents.

[IMPORTANT]
For Graphviz and PlantUML diagram generation, {uri-graphviz}[Graphviz] must be installed (i.e., the `dot` utility must be available on your `$PATH`.

=== Installation

Using Bundler::
+
--
Add `asciidoctor-diagram` gem to your [path]_Gemfile_

[source,ruby]
----
group :jekyll_plugins do
  ...
  gem 'asciidoctor-diagram', '~> 1.4.0' <1>
  ...
end
----
<1> version can be configured differently

Then, run the Bundler command to install it:

 $ bundle install
--

Without Bundler::
+
--
Install gems manually

 $ gem install asciidoctor-diagram

Then, add the `asciidoctor-diagram` gem to the list of gems for Jekyll to load in your site's [path]_{empty}_config.yml_ file:

[source,yaml]
----
gems:
  - asciidoctor-diagram
  - jekyll-asciidoc
----
--

Both of the previous configurations are the equivalent of passing `-r asciidoctor-diagram` to the `asciidoctor` command.

=== Generated image location

By default diagram images are generated in the root folder.
Thus, images URLs are not properly referenced from the generated HTML pages.

To fix this, set the `imagesdir` attribute in any AsciiDoc file that contains diagrams.

._posts/2015-12-24-diagrams.adoc
[source,asciidoc]
----
= Diagrams
:imagesdir: /images/2015-12-24 <1>

[graphviz, dot-example, svg]
....
digraph g {
    a -> b
    b -> c
    c -> d
    d -> a
}
....
----
<1> the date in the imagesdir value must match the date of the post (e.g., 2015-12-24)

WARNING: The images are generated after Jekyll copies assets to the [path]_{empty}_site_ directory.
Therefore, you'll have to run `jeykll` twice before you see the images in the preview.

== Supplemental AsciiDoc Assets

Certain Asciidoctor features, such as icons, require additional CSS rules and other assets to work.
These CSS rules and other assets do not get automatically included in the pages generated by Jekyll.
This section documents how to configure these additional resources.

TIP: If you want to take a shortcut that skips all this configuration, clone the https://github.com/asciidoctor/jekyll-asciidoc-quickstart[Jekyll AsciiDoc Quickstart (JAQ)] repository and use it as a starting point for your site.
JAQ provides a page layout out of the box configured to fully style body content generated from AsciiDoc.

=== Setup

The Jekyll AsciiDoc plugin converts AsciiDoc to embeddable HTML.
This HTML is then inserted into the page layout.
You need to augment the page layout to include resources typically present in a standalone HTML document that Asciidoctor produces.

. Create a stylesheet in the [path]_css_ directory named [path]_asciidoc.css_ to hold additional CSS for body content generated from AsciiDoc.
. Add this stylesheet to the HTML `<head>` in [path]_{empty}_includes/head.html_ under the main.css declaration:
+
[source,html]
----
<link rel="stylesheet" href="{{ "/css/asciidoc.css" | prepend: site.baseurl }}">
----

=== Font-based Admonition and Inline Icons

To enable font-based admonition and inline icons, you first need to add Font Awesome to [path]_{empty}_includes/head.html_ file under the asciidoc.css declaration:

[source,html]
----
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css">
----

NOTE: You can also link to local copy of Font Awesome.

Next, you need to add the following CSS rules from the default Asciidoctor stylesheet to the [path]_css/asciidoc.css_ file:

[source,css]
----
span.icon>.fa {
  cursor: default;
}
.admonitionblock td.icon {
  text-align: center;
  width: 80px;
}
.admonitionblock td.icon [class^="fa icon-"] {
  font-size: 2.5em;
  text-shadow: 1px 1px 2px rgba(0,0,0,.5);
  cursor: default;
}
.admonitionblock td.icon .icon-note:before {
  content: "\f05a";
  color: #19407c;
}
.admonitionblock td.icon .icon-tip:before {
  content: "\f0eb";
  text-shadow: 1px 1px 2px rgba(155,155,0,.8);
  color: #111;
}
.admonitionblock td.icon .icon-warning:before {
  content: "\f071";
  color: #bf6900;
}
.admonitionblock td.icon .icon-caution:before {
  content: "\f06d";
  color: #bf3400;
}
.admonitionblock td.icon .icon-important:before {
  content: "\f06a";
  color: #bf0000;
}
----

Feel free to modify the CSS to your liking.

Finally, you need to enable the font-based icons in the header of the document:

[source,asciidoc]
----
:icons: font
----

or in the site configuration:

[source,yaml]
----
asciidoctor:
  attributes:
    - icons=font
    ...
----

=== Image-based Admonition and Inline Icons

As an alternative to font-based icons, you can configure Asciidoctor to use image-based icons.
In this case, all you need to do is provide the icons at the proper location.

First, enable image-based icons and configure the path to the icons in the header of the document:

[source,asciidoc]
----
:icons:
:iconsdir: /images/icons
----

or your site configuration:

[source,yaml]
----
asciidoctor:
  attributes:
    - icons
    - iconsdir=/images/icons
----

Then, simply put the icon images that the page needs in the [path]_images/icons_ directory.

== GitHub Pages

GitHub doesn't (yet) whitelist the AsciiDoc plugin, so you can only run it on your own machine.

TIP: GitHub needs to hear from enough users that they want to plugin in order to enable it.
Our recommendation is to keep lobbying for them to enable it.

You can automate publishing of the generated site to GitHub Pages using a continuous integration job.
Refer to the tutorial http://eshepelyuk.github.io/2014/10/28/automate-github-pages-travisci.html[Automate GitHub Pages publishing with Jekyll and Travis CI^] to find step-by-step instructions to setup this job.
You can also refer to the https://github.com/johncarl81/transfuse-site[Tranfuse website build^] for an example in practice.

Refer to the https://help.github.com/articles/using-jekyll-plugins-with-github-pages[Jekyll Plugins on GitHub Pages] for a list of the plugins currently supported on the server-side (in addition to Markdown, which isn't listed).

== Releasing the gem to RubyGems.org

When you are ready for a release, first set the version in the file [path]_lib/jekyll-asciidoc/version.rb_.
Then, commit the change using the following commit message template:

 Release X.Y.Z

where `X.Y.Z` is the version number of the gem.

Next, package, tag and release the gem to RubyGems.org, run the following rake task:

 $ rake release

IMPORTANT: Ensure you have the proper credentials setup as described in the guide http://guides.rubygems.org/publishing/#publishing-to-rubygemsorg[Publishing to RubyGems.org].

Once you finish the release, you should update the version to the next micro version in the sequence using the `.dev` suffix (e.g., 1.0.1.dev).
