= Jekyll AsciiDoc Plugin (powered by Asciidoctor)
Paul Rayner <https://github.com/paulrayner[@paulrayner]>; Dan Allen <https://github.com/mojavelinux[@mojavelinux]>

A plugin for http://jekyllrb.com[Jekyll] that converts http://asciidoc.org[AsciiDoc] files in your site source to HTML pages using http://asciidoctor.org[Asciidoctor].

== Overview

The plugin consists of three extensions:

`Jekyll::Converters::AsciiDocConverter`::
  Converts AsciiDoc files to HTML
`Jekyll::Generators::AsciiDocPreprocessor`::
  Promotes select AsciiDoc attributes to Jekyll front matter (e.g., title, author, page-layout)
`Jekyll::Filters.asciidocify`::
  A Liquid filter for converting AsciiDoc content to HTML using the AsciiDocConverter

These extensions are loaded automatically when the jekyll-asciidoc is required.

== Installation

The plugin depends on the http://rubygems.org/gems/asciidoctor[asciidoctor] gem.
You can install the gem using:

 $ gem install asciidoctor

If you're using Bundler to manage the dependencies in your Jekyll project, instead add the asciidoctor gem to your [path]_Gemfile_ (beneath the jekyll gem):

[source,ruby]
----
source 'https://rubygems.org'

gem 'jekyll'
gem 'asciidoctor'
----

Then, run the Bundler install command:

 $ bundle install

=== Installing a released version of the plugin

Using Bundler::
+
--
Add the `jekyll-asciidoc` plugin gem to your [path]_Gemfile_

[source,ruby]
----
group :jekyll_plugins do
  gem 'jekyll-asciidoc'
end
----

Then, run the Bundler command to install it:

 $ bundle install
--

Without Bundler::
+
--
If you are not using Bundler for managing Jekyll then install gems manually

 $ gem install jekyll-asciidoc 

And then, add the `jekyll-asciidoc` gem to the list of gems for Jekyll to load in your site's [path]_{empty}_config.yml_ file:

[source,yaml]
----
gems:
  - jekyll-asciidoc
----
--

=== Installing development version of the plugin

To install the development version of this plugin, use:

 $ rake install

An alternative--though not recommend--approach is to copy the file [path]_lib/jekyll-asciidoc.rb_ to the [path]_{empty}_plugins_ directory in the root of your site source.

NOTE: If the [path]_{empty}_plugins_ directory does not exist, you need to first create it.

== Creating Pages

To add a page composed in AsciiDoc, simply add an AsciiDoc file to the root of the project with an AsciiDoc file extension.

.sample.adoc
[source,asciidoc]
....
---
---
= Sample Page
:layout: page
:permalink: /page/

This is a sample page composed in AsciiDoc.
Jekyll converts it to HTML using http://asciidoctor.org[Asciidoctor].

[source,ruby]
----
puts "Hello, World!"
----
....

IMPORTANT: The AsciiDoc file must have a http://jekyllrb.com/docs/frontmatter/[YAML front matter] header or else it won't be recognized as a page.
You can use an empty front matter header, as shown above, or you can define all your document metadata (e.g., document title) in the front matter instead of AsciiDoc attributes.

You can now build your site using:

 $ jekyll build
 
and preview it using:

 $ jekyll serve

If you are using Bundler then use following commands to do the same

 $ bundle exec jekyll build
 $ bundle exec jekyll serve
 
IMPORTANT: If you use the `--safe` option, the AsciiDoc plugin will not be activated.
The `--safe` flag disables third-party plugins such as this one.

== Configuration (Optional)

By default, this plugin uses Asciidoctor to convert AsciiDoc files.
Since Asciidoctor is the only option, the default setting is equivalent to the following configuration in [path]_{empty}_config.yml_:

[source,yaml]
asciidoc: asciidoctor

To tell Jekyll which extensions to recognize as AsciiDoc files, add the following line to your [path]_{empty}_config.yml_:

[source,yaml]
asciidoc_ext: asciidoc,adoc,ad

The extensions shown in the previous listing are the default values, so you don't need to specify this option if those defaults are sufficient.

To pass additional attributes to AsciiDoc, or override the default attributes defined in the plugin, add the following lines to your [path]_{empty}_config.yml_:

[source,yaml]
asciidoctor:
  attributes:
    - hardbreaks!
    - source-highlighter=pygments
    - pygments-css=style

=== Hard line breaks

The Jekyll AsciiDoc integration is configured to preserve hard line breaks in paragraph content by default.
Since many Jekyll users are used to writing in GitHub-flavored Markdown (GFM), this default was selected to ease the transition to AsciiDoc.
If you want the standard AsciiDoc behavior of collapsing hard line breaks in paragraph content, add the following settings to your site's [path]_{empty}_config.yml_ file:

[source,yaml]
asciidoctor:
  attributes:
    - hardbreaks!

If you already have AsciiDoc attributes defined in the [path]_{empty}_config.yml_, the `hardbreaks!` attribute should be added as a sibling entry in the YAML collection.

== GitHub Pages

GitHub doesn't (yet) whitelist the AsciiDoc plugin, so you can only run it on your own machine.

TIP: GitHub needs to hear from enough users that they want to plugin in order to enable it.
Our recommendation is to keep lobbying for them to enable it.

You can automate publishing of the generated site to GitHub Pages using a continuous integration job.
Refer to the tutorial http://eshepelyuk.github.io/2014/10/28/automate-github-pages-travisci.html[Automate GitHub Pages publishing with Jekyll and Travis CI^] to find step-by-step instructions to setup this job.
You can also refer to the https://github.com/johncarl81/transfuse/tree/transfuse-jeykll-site[Tranfuse website build^] for an example in practice.

Refer to the https://help.github.com/articles/using-jekyll-plugins-with-github-pages[Jekyll Plugins on GitHub Pages] for a list of the plugins currently supported on the server-side (in addition to Markdown, which isn't listed).

== Releasing the gem to RubyGems.org

When you are ready for a release, first set the version in the file [path]_lib/jekyll-asciidoc/version.rb_.
Then, commit the change using the following commit message template:

 Release X.Y.Z

where `X.Y.Z` is the version number of the gem.

Next, package, tag and release the gem to RubyGems.org, run the following rake task:

 $ rake release

IMPORTANT: Ensure you have the proper credentials setup as described in the guide http://guides.rubygems.org/publishing/#publishing-to-rubygemsorg[Publishing to RubyGems.org].

Once you finish the release, you should update the version to the next micro version in the sequence using the `.dev` suffix (e.g., 1.0.1.dev).
