= Enabling Asciidoctor Diagram

{url-asciidoctor-diagram}[Asciidoctor Diagram] is a set of extensions for Asciidoctor that allow you to embed diagrams generated by PlantUML, Graphviz, ditaa, Shaape, and other plain-text diagram tools inside your AsciiDoc documents.
In order to use Asciidoctor Diagram in a Jekyll project successfully, *you must use a version of this plugin >= 2.0.0*.
Other combinations are known to have issues.

IMPORTANT: For Graphviz and PlantUML diagram generation, {url-graphviz}[Graphviz] must be installed (i.e., the `dot` utility must be available on your `$PATH`.

TIP: To follow a start-to-finish tutorial that covers how to integrate Asciidoctor Diagram, see https://gist.github.com/mojavelinux/968623c493190dd61c059c2d85f9bdc3[this gist].

== Installation

Using Bundler::
+
--
Add the `asciidoctor-diagram` gem to your [.path]_Gemfile_:

[source,ruby,subs=attributes+]
----
group :jekyll_plugins do
  gem 'asciidoctor-diagram', '~> 1.5.4' #{conum-guard}<1>
  gem 'jekyll-asciidoc'
  ...
end
----
<1> Customize the version of Asciidoctor Diagram as needed.

Then, run Bundler's install command to install the new gem:

 $ bundle
--

Without Bundler::
+
--
Install gems manually

 $ [sudo] gem install asciidoctor-diagram

Then, add the `asciidoctor-diagram` gem to the list of plugins for Jekyll to load in your site's {path-config} file:

[source,yaml]
----
plugins:
- asciidoctor-diagram
- jekyll-asciidoc
----

If you're running Jekyll < 3.5.0, you'll need to use `gems` in place of `plugins`:

[source,yaml]
----
gems:
- asciidoctor-diagram
- jekyll-asciidoc
----
--

The preceding configurations are equivalent to passing `-r asciidoctor-diagram` to the `asciidoctor` command.

== Generated Image Location

Asciidoctor Diagram needs some context in order to write the images to the proper location.
At a minimum, you must set the following configuration in {path-config}:

[source,yaml]
----
asciidoctor:
  base_dir: :docdir
  safe: unsafe
----

With this configuration, Asciidoctor Diagram will generate images relative to the generated HTML page (i.e., in the same directory) within the destination folder.

WARNING: Jekyll will *delete* the images Asciidoctor Diagram generates unless you follow the instructions in <<Preserving Generated Images>>.

You can use the following example to test your setup:

._posts/2016-01-01-diagram-sample.adoc
[source,asciidoc]
----
= Diagram Sample

[graphviz,dot-example,svg]
....
digraph g {
    a -> b
    b -> c
    c -> d
    d -> a
}
....
----

If you prefer to serve all images from the same folder, assign a value to the `imagesdir` attribute that is relative to the site root:

[source,yaml]
----
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    imagesdir: /images
----

With this configuration, Asciidoctor Diagram will generate images into the [.path]_images_ directory within the destination folder.

WARNING: Jekyll will *delete* the images Asciidoctor Diagram generates unless you follow the instructions in <<Preserving Generated Images>>.

=== Preserving Generated Images

Since Asciidoctor Diagram writes to the output folder, you have to instruct Jekyll not to remove these generated files in the middle of the build process.
One way to do this is to apply a "`monkeypatch`" to Jekyll.
Add the file [.path]_jekyll-ext.rb_ to the [.path]__plugins_ folder of your project root (creating the folder if it does not already exist) and populate the file with the following content:

._plugins/jekyll-ext.rb
[source,ruby]
----
class Jekyll::Cleaner
  def cleanup!; end
end
----

An alternative to the monkeypath approach is to identify folders that contain generated images in the `keep_files` option in {path-config}:

[source,yaml]
----
keep_files:
- images
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    imagesdir: /images
----
