= Enabling Asciidoctor Diagram

xref:diagram-extension::index.adoc[] is an Asciidoctor extension providing numerous block and blockMacro processors that allow you to embed diagrams generated by PlantUML, Graphviz, ditaa, Shaape, and other plain-text diagram tools inside your AsciiDoc documents.

Consult xref:diagram-extension::index.adoc#specifying-diagram-generator-paths[this] for information about what external tools you may need to install for particular diagram types.

TIP: To follow a rather old start-to-finish tutorial that covers how to integrate Asciidoctor Diagram, see https://gist.github.com/mojavelinux/968623c493190dd61c059c2d85f9bdc3[this gist].

== Installation

Using Bundler::
+
--
Add the `asciidoctor-diagram` gem to your `Gemfile`:

[source,ruby,subs=attributes+]
----
group :jekyll_plugins do
  gem 'asciidoctor-diagram', '~> 2.1.0' #{conum-guard}<1>
  gem 'jekyll-asciidoc' #{conum-guard}<2>
  ...
end
----
<1> Customize the version of Asciidoctor Diagram as needed.
<2> Since an Asciidoctor extension does not communicate directly with Jekyll, it does not need to know about the Jekyll page variables set up by `jekyll-asciidoc` and may be listed before `jekyll-asciidoc`.

Then, run Bundler's install command to install the new gem:

 $ bundle
--

Without Bundler::
+
--
Install gems manually

 $ [sudo] gem install asciidoctor-diagram

Then, add the `asciidoctor-diagram` gem to the list of plugins for Jekyll to load in your site's `_config.yml` file:

[source,yaml]
----
plugins:
- asciidoctor-diagram
- jekyll-asciidoc
----

If you're running Jekyll < 3.5.0, you'll need to use `gems` in place of `plugins`:

[source,yaml]
----
gems:
- asciidoctor-diagram
- jekyll-asciidoc
----
--

This results in xref:diagram-extension::index.adoc#enabling-extensions[installing all available diagram converters].
There is no easy way to install only one or a subset.

== Generated Image Location and reference configuration

Asciidoctor Diagram can either store the generated image as a file in a configured location, so that your document can refer to it with an external link from an `<img>` tag or, for an interactive svg, an `<object>` tag, or include the image data directly in the rendered document, as a `data-uri` or an inline svg.

=== Generated images as files

Jekyll assumes that it will generate all site content, so it feels free to delete anything it didn't generate.
If asciidoctor-diagram is configured to generate files (the default), Jekyll must be prevented from deleting these generated files.
See <<preserving-generated-images>>

Asciidoctor Diagram needs some context in order to write the images to the proper location.
At a minimum, you must set the following configuration in `_config.yml`:

[source,yaml]
----
asciidoctor:
  base_dir: :docdir
  safe: unsafe
----

With this configuration, Asciidoctor Diagram will generate images relative to the generated HTML page (i.e., in the same directory) within the destination folder.

WARNING: Jekyll will *delete* the images Asciidoctor Diagram generates unless you follow the instructions in <<Preserving Generated Images>>.

If you prefer to serve all images from the same folder, assign a value to the `imagesdir` attribute that is relative to the site root:

[source,yaml]
----
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    imagesdir: /images
----

With this configuration, Asciidoctor Diagram will generate images into the `_images` directory within the destination folder.

WARNING: Jekyll will *delete* the images Asciidoctor Diagram generates unless you follow the instructions in <<Preserving Generated Images>>.

==== Preserving Generated Images

Since Asciidoctor Diagram writes to the output folder, you have to instruct Jekyll not to remove these generated files in the middle of the build process.
One way to do this is to apply a "`monkeypatch`" to Jekyll.
Add the file `jekyll-ext.rb to the `_plugins` folder of your project root (creating the folder if it does not already exist) and populate the file with the following content:

._plugins/jekyll-ext.rb
[source,ruby]
----
class Jekyll::Cleaner
  def cleanup!; end
end
----

An alternative to the monkeypatch approach is to identify folders that contain generated images in the `keep_files` option in `_config.yml`:

[source,yaml]
----
keep_files:
- images
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    imagesdir: /images
----

=== Embedded in the rendered document

==== `data-uri` approach

This results in the image data (binary or text) being base-64 encoded into a string which is included in the html output.
This is most suitable for small images used once.
Large images may unduly slow page loading or exceed browser size limits.
Multiple uses of the same image will result in multiple copies of the same data-uri string.

To enable this feature, the `data-uri` attribute must be set at the image location in the document.
This can be done:

* Globally in `_config.yml`:
[source,yml]
----
asciidoctor:
  attributes:
    data-uri@: '' <1>
----
<1> Recall that appending `@` after an attribute name allows the value to be overridden on individual pages.

// comment to force next list item out of conum list

* Per-page as a document attribute:
[source,adoc]
----
= My Fabulous Page
:data-uri:

My fascinating content.
----

* In the document before the image:
[source,adoc]
----
= My Fabulous Page

The intriging preface.

:data-uri:

----

==== Svg inline and interactive approach

The effect of different svg strategies is discussed xref:asciidoc:macros:image-svg.adoc[here], although the way of specifying them differs.

For asciidoctor-diagram these are controlled by variants of the xref:diagram-extension::index.adoc#shared-attributes[`svg-type` attribute].
As with the `data-uri` attribute these may be specified globally, in the document header, or in the document body.
In addition, the unprefixed `svg-type` attribute may be specified as a block named attribute:

[source,adoc]
....
[svgbob,,svg,svg-type=inline] <1>
----
...
----
....
<1> Since there is no need to specify the `target` positional attribute, it is omitted via the `,,`.
Alternatively, we could use the attribute name: `[svgbob,format=svg,svg-type=inline]`.

== Example

You can use the following example to test your setup:

._posts/2016-01-01-diagram-sample.adoc
[source,asciidoc]
----
= Diagram Sample

[graphviz,dot-example,svg]
....
digraph g {
    a -> b
    b -> c
    c -> d
    d -> a
}
....
----

