= Asciidoctor

In addition to the built-in attributes in AsciiDoc, the following additional AsciiDoc attributes are automatically defined by this plugin and available to all AsciiDoc-based pages:

....
site-root=(absolute path of root directory)
site-source=(absolute path of source directory)
site-destination=(absolute path of output directory)
site-baseurl=(value of the baseurl config option)
site-url=(value of the url config option)
env=site
env-site
site-gen=jekyll
site-gen-jekyll
builder=jekyll
builder-jekyll
jekyll-version=(value of the Jekyll::VERSION constant)
idprefix
idseparator=-
linkattrs=@
....

The following additional attributes are defined per page:

....
outpath=(path of page relative to baseurl)
....

You can pass custom attributes to AsciiDoc, or override default attributes provided by the plugin, using the `attributes` option of the `asciidoctor` block in your {path-config}.
The value of this option can either be an Array containing key-value pairs:

[source,yaml]
----
asciidoctor:
  attributes:
  - idprefix=_
  - source-highlighter=pygments
  - pygments-css=style
----

or key-value pairs defined as a Hash:

[source,yaml]
----
asciidoctor:
  attributes:
    idprefix: _
    source-highlighter: pygments
    pygments-css: style
----

When using the Hash syntax, you must use an empty string value to set a valueless attribute such as `sectanchors`:

[source,yaml]
----
asciidoctor:
  attributes:
    sectanchors: ''
----

By default, an attribute value defined in {path-config} overrides the same attribute set in the front matter or header of a document.
For example, if you set `page-layout` in {path-config}, you won't be able to set it per page.

[source,yaml]
----
asciidoctor:
  attributes:
  - page-layout=false
----

If you want to allow individual pages to be able to override the attribute, append the charcter `@` to the value in {path-config}:

[source,yaml]
----
asciidoctor:
  attributes:
  - page-layout=false@
----

You may use attribute references in the attribute value to reference any attribute that's already defined, including implicit attributes.
For example, to set the `iconsdir` attribute based on the `imagesdir` attribute, use the following:

[source,yaml]
----
asciidoctor:
  attributes:
    imagesdir: /images
    iconsdir: '{imagesdir}/icons'
----

CAUTION: If the value begins with an attribute reference, and you're defining the attributes using the Hash syntax, you must enclose the value in quotes.
There are additional edge cases when the value must be enclosed in quotes, so it's generally recommended to use them.

Since version 2.1.0 of this plugin, you can remove a previously defined attribute by prefixing the name with a minus sign (without any space between):

[source,yaml]
----
asciidoctor:
  attributes:
    -idprefix:
----

In addition to `attributes`, you may define any other option key (e.g., `safe`) in the Asciidoctor xref:asciidoctor:api:options.adoc[].
One of those options is `base_dir`, which is covered in the next section.

