= Specifying the Base Directory

In Asciidoctor, the base directory (i.e., `base_dir` option) is used as the root when resolving relative include paths in top-level documents.

By default, this plugin does not specify a base directory when invoking the Asciidoctor API.
Asciidoctor will therefore use the current working directory (i.e., the project root) as the base directory.

If your source directory is not the project root, and you want Asciidoctor to use the source directory as the base directory, set the value of the `base_dir` option to `:source`.

[source,yaml]
----
asciidoctor:
  base_dir: :source
  ...
----

If, instead, you want the base directory to track the directory of the document being processed you can set the value of the `base_dir` option to `:docdir`.
This behavior matches how Asciidoctor works when running it outside of Jekyll.
Since the base directory is also the jail, we also recommend setting the `safe` option to enable unsafe mode so you can still resolve paths outside of this directory.

[source,yaml]
----
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  ...
----

You can also set the `base_dir` option to any relative or absolute path.
In that case, the same value will be used for all documents.

