= Configuration

This section describes the configuration options for this plugin, which are _optional_.

You should at least assign an empty Hash as a default (e.g., `{}`) to the `asciidoc` and `asciidoctor` keys in `_config.yml`, respectively, if you don't plan on making any further customizations.

[source,yaml]
----
asciidoc: {}
asciidoctor: {}
----

Using these placeholder values prevents initialization from being performed more than once when using watch mode (see https://github.com/jekyll/jekyll/issues/4858[issue jekyll#4858]).

== AsciiDoc

NOTE: Prior to version 2.0.0 of this plugin, the configuration keys in this section were defined as flat, top-level names (e.g., `asciidoc_ext`).
These names are now deprecated, but still supported.

By default, this plugin uses Asciidoctor to convert AsciiDoc files.
Because Asciidoctor is currently the only option, the default setting is equivalent to the following configuration in `_config.yml`:

[source,yaml]
----
asciidoc:
  processor: asciidoctor
----

IMPORTANT: The `asciidoc` block should only appear _once_ inside `_config.yml`.
If you define any other options that are documented in this section, you should append them to the `asciidoc` block.

To tell Jekyll which file extensions to match as AsciiDoc files, append the `ext` option to the `asciidoc` block of your `_config.yml`:

[source,yaml]
----
asciidoc:
  ext: asciidoc,adoc,ad
----

The extensions shown in the previous listing are the default values, so you don't need to specify this option if those defaults are sufficient.

See xref:page-attributes.adoc[] for a discussion of the `page_attribute_prefix` key and page variables.

Since version 2.0.0 of this plugin, all non-hidden AsciiDoc files are processed by default, even those without a front matter header.
If you only want files containing a front matter header to be processed (as was the behavior prior to version 2.0.0), add the `require_front_matter_header` option to the `asciidoc` block of your `_config.yml`:

[source,yaml]
----
asciidoc:
  require_front_matter_header: true
----

