= Configuration

This section describes the configuration options for this plugin, which are _optional_.

You should at least assign an empty Hash as a default (e.g., `{}`) to the `asciidoc` and `asciidoctor` keys in `_config.yml`, respectively, if you don't plan on making any further customizations.

[source,yaml]
----
asciidoc: {}
asciidoctor: {}
----

Using these placeholder values prevents initialization from being performed more than once when using watch mode (see https://github.com/jekyll/jekyll/issues/4858[issue jekyll#4858]).

NOTE: This needs to be verified, as that issue is closed.

== Configuration location

There are two top level keys used for configuration of this plugin.

`asciidoc`::
The `asciidoc` key is used for configuration of the general relationship of Jekyll to this plugin, including the singular choice of Asciidoctor as the AsciiDoc processor.
`asciidoctor`::
The `asciidoctor` key is used for configuration of the Asciidoctor instance set up by this plugin.

In addition, xref:global-page-attributes.adoc[] can be set under either the `asciidoc` key or the `asciidoctor` key.
Through the xref:page-attributes.adoc[page attribute to page variable translation] this may result in global configuration of Jekyll page variables .

As with any YAML, these keys should appear at most once in your `_config.yml` file.

