= Extracting Excerpts

Unless the `page-excerpt` page attribute or the `excerpt` page variable is set, this plugin will extract an {url-jekyll-excerpts}[excerpt] for any post or document in a collection using the same logic as for Markdown files.
By default, it will use the content between the header (if present) or front matter (if present) and the next blank line.
If the `page-excerpt` page attribute or the `excerpt` page variable is set, that value will be used instead.
The excerpt will automatically be converted from AsciiDoc to embedded HTML whereever the `excerpt` property is referenced in a Liquid template.

----
{% post.excerpt %}
----

If you want to use a different excerpt separator for AsciiDoc files, set the `excerpt_separator` under the `asciidoc` key in the site configuration.
For example, you can configure the plugin to use the line comment `//more` as the excerpt separator as follows:

[source,yaml]
----
asciidoc:
  excerpt_separator: "\n//more\n"
----

If you're only working with AsciiDoc files in your site, you can go ahead and set this for all files by using the top-level property:

[source,yaml]
----
excerpt_separator: "\n//more\n"
----

If the excerpt separator isn't found, the content of the whole document is used instead.

By default, the excerpt is converted to HTML using the article doctype.
If you want to use a different doctype, such as inline, you can set it in the site configuration as follows:

[source,yaml]
----
asciidoc:
  excerpt_doctype: inline
----

You can also set the excerpt doctype per page using the page attribute named `page-excerpt_doctype`.
