= Enabling Asciidoctor Extensions

You enable Asciidoctor extensions in much the same way as this plugin.
You just need to configure Jekyll to load the source.

This process works for self-registering Asciidoctor extensions.
If you are using a published extension that is not self-registering, you will need to add registration code as an <<unpublished-extensions,unpublished extension>>.

== Extensions published as Gems

If the extension you want to use is published as a gem, and you're using Bundler to manage the dependencies for your project (as recommended), then you simply add the gem to the `jekyll_plugins` group in your `Gemfile`:

[source,ruby]
----
group :jekyll_plugins do
  gem 'asciidoctor-extension-xyz'
end
----

Then, run the `bundle` command from Bundler to install the gem:

 $ bundle

If you're not using Bundler to manage the dependencies for your Jekyll project, you'll need to install the gem manually.
Once that's done, add the gem to the list gems for Jekyll to load in your site's `_config.yml` file:

[source,ruby]
----
plugins:
- asciidoctor-extension-xyz
----

If you're running Jekyll < 3.5.0, you'll need to use `gems` in place of `plugins`:

[source,ruby]
----
gems:
- asciidoctor-extension-xyz
----

== Unpublished extensions

If the extension you want to use is not published as a gem, or is something you're developing, then you'll load it like an ad-hoc Jekyll plugin.
Add the file `asciidoctor-extensions.rb` to the `_plugins` folder of your project root (creating the folder if it does not already exist) and populate the file with the extension registration and implementation code, such as:

._plugins/asciidoctor-extensions.rb
[source,ruby]
----
require 'asciidoctor/extensions'

Asciidoctor::Extensions.register do
# registration code
  treeprocessor do
# processor implementation
    process do |doc|
      doc
    end
  end
end
----

Asciidoctor will automatically enable the extensions in this file when it is loaded by Jekyll.

For a concrete example of using an existing, published, Asciidoctor extension, refer to the next section.

