= Installation

== Prerequisites

To use this plugin, you must be using Jekyll >= 3.0.0 and Ruby >= 2.4.0 (with development headers installed).
You should also be familiar with creating sites with Jekyll.
If you're not, you should first read the {url-jekyll-docs}[Jekyll documentation] to familiarize yourself with how it works.
Experience with AsciiDoc and Asciidoctor is also helpful, but not a requirement.

Like Jekyll, this plugin was designed for developers, so some assembly is required.
That means you'll be expected to edit configuration, modify HTML templates, and customize CSS to use it fully.

== Installation

This plugin is packaged as a gem named {url-gem}[jekyll-asciidoc] and published to RubyGems.org.
The plugin depends on the {url-gem-asciidoctor}[asciidoctor] gem, which gets installed automatically.

Your method of installation will depend on whether you use Bundler to manage the dependencies for your Jekyll project.

IMPORTANT: Jekyll relies on several native gems, so it's necessary to have the Ruby development headers (e.g., ruby.h) on your machine in order to install AsciiDoc Jekyll (due to the requirements of Jekyll).
The instructions for how to install the Ruby development headers are platform-specific and outside of the scope of this document.

TIP: If you're using RVM, you should add a _.ruby-version_ file to the project so your shell automatically switches to the correct version of Ruby each time you enter the project.
For more information, refer to the the page https://rvm.io/workflow/projects[RVM Project Workflow].

=== Installation Using Bundler

If you're using Bundler to manage the dependencies for your project (as recommended), simply add the `jekyll-asciidoc` gem to the `:jekyll_plugins` group in your _Gemfile_:

[source,ruby]
----
group :jekyll_plugins do
  gem 'jekyll-asciidoc'
end
----

Then, run the `bundle` command from Bundler to install the gem:

 $ bundle

Jekyll will automatically activate any plugins listed in the `:jekyll_plugins` group.

If you want to keep the installed gems inside the project, use this command instead:

 $ bundle --path=.bundle/gems

TIP: Subsequent calls to `bundle` will retain the `path` setting.

Keep in mind that the gems Bundler installs are linked to the current version of Ruby.
If you switch Ruby versions, you'll need to run `bundle` again.

=== Manual Installation

If you're not using Bundler to manage the dependencies for your Jekyll project, you'll need to install the gem manually:

 $ [sudo] gem install jekyll-asciidoc

NOTE: The `sudo` prefix is only required if you are installing gems into your system.
To avoid this bad practice, we recommend using RVM (or another Ruby version manager), which sets up Ruby safely in your home directory.

Then add the [.app]*jekyll-asciidoc* gem to the list of gems for Jekyll to load in your site's `_config.yml` file:

[source,yaml]
----
plugins:
- jekyll-asciidoc
----

If you're running Jekyll < 3.5.0, you'll need to use `gems` in place of `plugins`:

[source,yaml]
----
gems:
- jekyll-asciidoc
----

== Plugin Ordering

Since the `jekyll-asciidoc` plugin promotes xref:page-attributes.adoc[] to the front matter, it must run first.
To make sure it does, rearrange the sequence of plugins in your Gemfile or `_config.yml` file so the `jekyll-asciidoc` plugin is listed before other plugins.
By doing so, other plugins will be able to access any front matter that this plugin assigns.

Let's consider the case of using the `jekyll-archives` plugin alongside the `jekyll-asciidoc` plugin.

[source,ruby]
----
group :jekyll_plugins do
  gem 'jekyll-asciidoc'
  gem 'jekyll-archives' <1>
end
----
<1> The `jekyll-archives` plugin should be listed after the `jekyll-asciidoc` plugin since it needs to access front matter that is promoted from the header of the AsciiDoc document.

