= Specifying a Layout

The most commonly defined page variable is `layout` (`page-layout` as an Asciidoc document attribute), which determines which template is used to wrap the generated content.
Consult the {url-jekyll-layouts}[Jekyll layout documentation] for details.
We will assume the default template location of `_layouts`.
Jekyll will look for a template file inside the `_layouts` folder whose root name matches the name of the layout.
For example, if the layout variable has the value `info`, Jekyll looks for a layout template at the path `_layouts/info.html`.

Here are the different ways to specify a layout using the AsciiDoc attribute page-layout:

`:page-layout: info`::
  Use the layout named `info` (e.g., `_layout/info.html`)
(unspecified)::
`:page-layout:`::
`:page-layout: _auto`::
  Use the automatic layout:
* `page` for pages,
* `post` for posts
* The singular form of the {url-jekyll-collections}[collection label] for a document.
For instance, if a collection `oddities` is defined in `_config.yml`, a document at `_oddities/my-oddity.adoc` will have the `odditie` layout applied.
* If the auto-selected layout isn't available, the layout `default` is used
`:!page-layout:`::
`:page-layout: false`::
  Don't use a layout; instead, generate a standalone HTML document using only Asciidoctor's capabilities.
`:page-layout: none`::
`:page-layout: ~` (deprecated)::
  Don't use a layout and produce embeddable HTML.

