= Specifying a Layout

The most commonly defined page variable is layout, which determines which template is used to wrap the generated content.
Jekyll will look for a template file inside the [.path]_{empty}_layouts_ folder whose root name matches the name of the layout.
For example, if the layout variable has the value `info`, Jekyll looks for a layout template at the path [.path]__layout/info.html_.

If the layout is empty, the auto-selected layout layout is used (documented in the list below).
If the layout is unset or `false`, the AsciiDoc processor will generate a standalone document.
In this case, the page will appear like an HTML file generated by the AsciiDoc processor directly (with the option `header_footer: true`).
If the layout is ~, no layout is applied.

To review, here are the different ways to specify a layout using the AsciiDoc attribute page-layout:

`:page-layout: info`::
  Use the layout named `info` (e.g., __layout/info.html_)
_not specified_, `:page-layout:` or `:page-layout: _auto`::
  Use the automatic layout (i.e., `page` for pages, `post` for posts, the singular form of the collection label for a document; if the auto-selected layout isn't available, the layout `default` is used)
`:!page-layout:` or `:page-layout: false`::
  Don't use a layout; instead, generate a standalone HTML document
`:page-layout: none` or (deprecated) `:page-layout: ~`::
  Don't use a layout or create a standalone HTML document (often produces an HTML fragment).

