= Enabling Liquid Preprocessing

Unlike other content files, the {url-jekyll-liquid-templates}[Liquid template preprocessor] is not applied to AsciiDoc files by default.
If you want the Liquid template preprocessor to be applied to an AsciiDoc file (prior to the content being passed to the AsciiDoc processor), you must enable it by setting the `liquid` page variable, shown here defined using a page attribute.

[source,asciidoc]
----
:page-liquid:
----

It is also possible to set the `page-liquid` asciidoc attribute globally in `_config.yml` or to set the `liquid` page variable directly in Jekyll front matter.

== Asciidoc Inclusions

The Liquid preprocessor does not process content included using the AsciiDoc include directive (see {url-issues}/166[#166]).

However, if those files are otherwise publishable, they are processed independently with the Liquid preprocessor and will appear in your site.
If this is not desired, exclude them from independent processing by one of:

* Placing them in an automatically excluded location, such as a directory starting with `_`, e.g. `_includes`.
* Naming them so as to be automatically excluded, such as starting the name with `_`, e.g. `_excluded-include.yml`.
* Configuring the link:https://jekyllrb.com/docs/configuration/options/[Jekyll excludes] so as to apply to the file.

== Liquid Inclusions

If you're using the Liquid include tag to include HTML into the AsciiDoc document, enclose it in a passthrough block.

----
++++
{% include file.html %}
++++
----

Otherwise Asciidoctor will escape the HTML.

