= Creating Pages

This plugin converts eligible AsciiDoc files located inside the source directory (by default, the project root) to HTML pages in the generated site.
There are a few conditions that must be met in order for an AsciiDoc file to be eligible:

. The file must have an AsciiDoc file extension (see xref:configuration.adoc[]).
. The name of the file must not begin with a dot (`.`) or an underscore (`_`).footnote:excluded_files[Hidden files and folders are automatically excluded by Jekyll.]
. The file must not be located in a folder whose name begins with a dot (`.`) or an underscore (`_`) (unless the folder is a designated collection, such as _posts).footnote:excluded_files[]

Here's a sample AsciiDoc file that meets these criteria:

.sample.adoc
[source,asciidoc]
----
= Sample Page
:page-layout: info
:page-permalink: /sample/
:url-asciidoctor: http://asciidoctor.org

This is a sample page composed in AsciiDoc.
Jekyll converts it to HTML using {url-asciidoctor}[Asciidoctor].
It is presented in the `{page-layout}` layout.

[source,ruby]
puts "Hello, World!"
----
We recommend defining Jekyll page variables as xref:page-attributes.adoc[].
However, it is also possible to define them in traditional Jekyll front matter.
In this case the variables will not be available as Asciidoc attributes:

.sample.adoc
[source,asciidoc]
----
---
layout: info
permalink: /sample/
---
= Sample Page
:url-asciidoctor: http://asciidoctor.org

This is a sample page composed in AsciiDoc.
Jekyll converts it to HTML using {url-asciidoctor}[Asciidoctor].
//It is presented in the `{page-layout}` layout. <1>

[source,ruby]
puts "Hello, World!"
----
<1> Since the layout is defined in the front matter, it is not available as an Asciidoc attribute.