name: Release
on:
  push:
    tags:
    - 'v*'
jobs:
  activate:
    if: github.repository == 'asciidoctor/jekyll-asciidoc'
    runs-on: ubuntu-latest
    steps:
    - run: echo ok go
  build:
    needs: activate
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
    - name: Configure Bundler
      run: |
        bundle config --local path .bundle/gems
        bundle config --local without coverage docs
    - name: Install dependencies
      run: bundle --jobs 3 --retry 3
    - name: Run tests
      run: bundle exec rake test:all
    - name: Configure credentials
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${RUBYGEMS_API_KEY}" > $HOME/.gem/credentials
      env:
        RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
    - name: Build gem
      run: |
        bundle exec rake build
      working-directory: ./ruby
    - name: Publish to rubygems.org
      run: |
        gem push pkg/jekyll-asciidoc-${GITHUB_REF#refs/tags/ruby-v}.gem
      working-directory: ./ruby
